
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muhta
 */
public class StartupScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartupScreen
     */
    
    
    public StartupScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        TextChat = new javax.swing.JButton();
        VideoChat = new javax.swing.JButton();
        AudioChat = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button1.png"))); // NOI18N
        TextChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TextChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TextChatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TextChatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TextChatMouseReleased(evt);
            }
        });
        TextChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextChatActionPerformed(evt);
            }
        });

        VideoChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images1/2button1.png"))); // NOI18N
        VideoChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VideoChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VideoChatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VideoChatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                VideoChatMouseReleased(evt);
            }
        });
        VideoChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoChatActionPerformed(evt);
            }
        });

        AudioChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images3/3Button1.png"))); // NOI18N
        AudioChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AudioChatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AudioChatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AudioChatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AudioChatMouseReleased(evt);
            }
        });
        AudioChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AudioChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextChat, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AudioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VideoChat, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TextChat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(VideoChat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AudioChat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    private void TextChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextChatMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/Button2.png"));
        TextChat.setIcon(II);
    }//GEN-LAST:event_TextChatMouseEntered

    private void TextChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextChatMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/Button1.png"));
        TextChat.setIcon(II);
    }//GEN-LAST:event_TextChatMouseExited

    private void TextChatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextChatMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/Button3.png"));
        TextChat.setIcon(II);
    }//GEN-LAST:event_TextChatMousePressed

    private void TextChatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextChatMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images/Button1.png"));
        TextChat.setIcon(II);
    }//GEN-LAST:event_TextChatMouseReleased

    private void TextChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextChatActionPerformed
        dispose();
        new ServerClient().setVisible(true);
        
        
    }//GEN-LAST:event_TextChatActionPerformed

    private void AudioChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AudioChatActionPerformed
        dispose();
        new AudioStreamConnect().setVisible(true);
    }//GEN-LAST:event_AudioChatActionPerformed

    private void VideoChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideoChatMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Images1/2Button2.png"));
        VideoChat.setIcon(II);
    }//GEN-LAST:event_VideoChatMouseEntered

    private void VideoChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideoChatMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Images1/2Button1.png"));
        VideoChat.setIcon(II);
    }//GEN-LAST:event_VideoChatMouseExited

    private void VideoChatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideoChatMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images1/2Button3.png"));
        VideoChat.setIcon(II);
    }//GEN-LAST:event_VideoChatMousePressed

    private void VideoChatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideoChatMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images1/2Button1.png"));
        VideoChat.setIcon(II);
    }//GEN-LAST:event_VideoChatMouseReleased

    private void AudioChatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudioChatMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/Images3/3Button2.png"));
        AudioChat.setIcon(II);
    }//GEN-LAST:event_AudioChatMouseEntered

    private void AudioChatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudioChatMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/Images3/3Button1.png"));
        AudioChat.setIcon(II);
    }//GEN-LAST:event_AudioChatMouseExited

    private void AudioChatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudioChatMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/Images3/3Button3.png"));
        AudioChat.setIcon(II);
    }//GEN-LAST:event_AudioChatMousePressed

    private void AudioChatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudioChatMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/Images3/3Button1.png"));
        AudioChat.setIcon(II);
    }//GEN-LAST:event_AudioChatMouseReleased

    private void VideoChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoChatActionPerformed
            dispose();
            new VideoStreamConnect().setVisible(true);
    }//GEN-LAST:event_VideoChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartupScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AudioChat;
    private javax.swing.JButton TextChat;
    private javax.swing.JButton VideoChat;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
